#requires -Version 7.0
# Module entry point. Dot-sources every library file and exports the public API.

$ErrorActionPreference = 'Stop'

# lib holds the core; gui holds the phase 2 browser layer. Both are plain
# function definitions — nothing here starts a listener or opens a port.
foreach ($dir in @('lib', 'gui')) {
    $path = Join-Path $PSScriptRoot $dir
    if (Test-Path -LiteralPath $path) {
        Get-ChildItem -LiteralPath $path -Filter '*.ps1' | ForEach-Object { . $_.FullName }
    }
}

Export-ModuleMember -Function @(
    'ConvertTo-ProjectDirName'
    'Get-UserHome'
    'Get-ClaudExtPlatform'
    'Test-ClaudExtWindowsStylePath'
    'Test-PathWithinRoot'
    'Get-ClaudExtTrimmedPath'
    'Get-ClaudExtSharedPrefixLength'
    'Get-ClaudExtPathKey'
    'ConvertTo-MappedPath'
    'ConvertTo-RestoreMapping'
    'Get-ClaudExtMinimalMapping'
    'Resolve-ProjectDirName'
    'Get-RestoreRelativePath'
    'Expand-ClaudExtPath'
    'Get-ClaudeLocation'
    'Resolve-ClaudExtFullPath'
    'ConvertTo-CanonicalPath'
    'Resolve-ManifestPath'
    'Get-ClaudExtManifest'
    'Get-AutoMemorySource'
    'Get-ClaudExtSourceFiles'
    'Get-SourceStat'
    'Get-ProjectPaths'
    'Get-ProjectDirectoryMap'
    'Get-ClaudExtRecordedHome'
    'Get-ClaudeCodeVersion'
    'New-PathRemapper'
    'Test-ClaudExtTextFile'
    'Get-ClaudExtRemapMode'
    'Invoke-ClaudExtUtf16Remap'
    'ConvertTo-RemappedText'
    'ConvertTo-RemappedJsonValue'
    'New-PathMapping'
    'Invoke-FileRemap'
    'Read-ClaudExtJson'
    'ConvertFrom-ClaudExtJson'
    'Merge-JsonPortableKeys'
    'Export-JsonPortableKeys'
    'Invoke-SafeCollector'
    'Get-InstalledProgram'
    'Get-PlatformCollector'
    'Get-ClaudePluginList'
    'New-InventoryReport'
    'New-BackupArchive'
    'Test-BackupArchive'
    'Expand-BackupArchive'
    'Copy-Source'
    'New-BackupManifestFile'
    'Compare-RestoreCount'
    'Get-ClaudExtToolFiles'
    'Test-ClaudExtTool'
    'Sync-ClaudExtTool'

    # gui
    'New-ClaudExtToken'
    'Test-ClaudExtToken'
    'Test-ClaudExtOrigin'
    'Start-ClaudExtJob'
    'Get-ClaudExtJob'
    'Test-ClaudExtJobRunning'
    'Get-ClaudExtRunningJobId'
    'Get-ClaudExtLatestJobId'
    'Clear-ClaudExtJobs'
    'Invoke-ClaudExtBackup'
    'Invoke-ClaudExtRestore'
    'Get-ArchiveExtraSource'
    'Get-RestoreDecisionRows'
    'Test-ClaudExtMemoryDestination'
    'Resolve-ClaudExtRealPath'
    'Resolve-RestoreTarget'
    'Invoke-GuiBackup'
    'Invoke-GuiRestore'
    'Invoke-ApiInfo'
    'Test-ClaudeRunning'
    'Invoke-ApiTool'
    'Invoke-ApiSources'
    'Invoke-ApiBrowse'
    'Invoke-ApiArchive'
    'Invoke-ApiMapping'
    'Invoke-ApiBackup'
    'Invoke-ApiRestore'
    'Invoke-ApiJob'
    'Invoke-ApiShutdown'
    'Test-RestoreMappingComplete'
    'Resolve-ApiRoute'
    'ConvertFrom-QueryString'
    'Start-ClaudExtServer'
)
